---
- name: Install Grafana Agent
  hosts: all
  become: true

  vars:
    grafana_agent_version: "0.39.1"
    prometheus_remote_write_url: "http://83e8ed98-7e32-49e6-bb5e-8fa9450be47c.k8s.civo.com:30080/api/v1/write"

  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name: 
          - gpg
          - apt-transport-https
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Grafana GPG key
      ansible.builtin.apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: present
        filename: grafana

    - name: Install Grafana Agent
      ansible.builtin.apt:
        name: grafana-agent
        state: present
        update_cache: yes

    - name: Create agent config directory
      ansible.builtin.file:
        path: /etc/grafana-agent
        state: directory
        mode: '0755'

    - name: Configure Grafana Agent
      copy:
        dest: /etc/grafana-agent.yaml
        content: |
          server:
            log_level: debug
          metrics:
            global:
              scrape_interval: 15s  # Interval to scrape metrics
            configs:
              - name: prometheus
                # Scraping configuration for Node Exporter
                scrape_configs:
                  - job_name: node
                    static_configs:
                      - targets: ['localhost:9100']  # Node Exporter metrics endpoint
                    relabel_configs:
                      - source_labels: [__address__]
                        target_label: instance
                        replacement: "grafana-agent-instance" 
                # Remote write configuration to send metrics to Prometheus
                remote_write:
                  - url: "http://74.220.26.89:31090/api/v1/write"
          integrations:
            # Node Exporter integration for system metrics
            node_exporter:
              enabled: true
              include_exporter_metrics: true

    - name: Start and enable Grafana Agent
      ansible.builtin.systemd:
        name: grafana-agent
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Verify Grafana Agent is running
      wait_for:
        port: 9090
        timeout: 30